/**
 * Sample Car Data for Testing Advanced Search
 *
 * This file contains realistic car rental data with all required fields
 * including location data for map visualization
 */

const sampleCars = [
    {
        model: "Tesla Model 3",
        carModel: "Tesla Model 3",
        brand: "Tesla",
        type: "Sedan",
        price: 85,
        dailyRentalPrice: 85,
        transmission: "Automatic",
        fuel: "Electric",
        fuelType: "Electric",
        seats: 5,
        rating: 4.8,
        availability: "Available",
        image: "https://images.unsplash.com/photo-1560958089-b8a1929cea89?w=800",
        imageUrl:
            "https://images.unsplash.com/photo-1560958089-b8a1929cea89?w=800",
        location: {
            lat: 23.8103,
            lng: 90.4125,
            address: "Gulshan, Dhaka",
        },
        userName: "Sarah Wilson",
        userEmail: "sarah@example.com",
        bookingCount: 24,
        description: "Premium electric sedan with autopilot features",
        dateAdded: new Date("2024-10-15T10:30:00Z"),
    },
    {
        model: "Honda CR-V",
        carModel: "Honda CR-V",
        brand: "Honda",
        type: "SUV",
        price: 65,
        dailyRentalPrice: 65,
        transmission: "Automatic",
        fuel: "Petrol",
        fuelType: "Petrol",
        seats: 7,
        rating: 4.6,
        availability: "Available",
        image: "https://images.unsplash.com/photo-1519641471654-76ce0107ad1b?w=800",
        imageUrl:
            "https://images.unsplash.com/photo-1519641471654-76ce0107ad1b?w=800",
        location: {
            lat: 23.7461,
            lng: 90.3742,
            address: "Dhanmondi, Dhaka",
        },
        userName: "Mike Johnson",
        userEmail: "mike@example.com",
        bookingCount: 18,
        description: "Spacious family SUV with excellent safety features",
        dateAdded: new Date("2024-10-18T14:20:00Z"),
    },
    {
        model: "Toyota Camry",
        carModel: "Toyota Camry",
        brand: "Toyota",
        type: "Sedan",
        price: 50,
        dailyRentalPrice: 50,
        transmission: "Automatic",
        fuel: "Petrol",
        fuelType: "Petrol",
        seats: 5,
        rating: 4.5,
        availability: "Available",
        image: "https://images.unsplash.com/photo-1621007947382-bb3c3994e3fb?w=800",
        imageUrl:
            "https://images.unsplash.com/photo-1621007947382-bb3c3994e3fb?w=800",
        location: {
            lat: 23.8759,
            lng: 90.3795,
            address: "Uttara, Dhaka",
        },
        userName: "John Smith",
        userEmail: "john@example.com",
        bookingCount: 32,
        description: "Reliable and comfortable mid-size sedan",
        dateAdded: new Date("2024-10-20T09:15:00Z"),
    },
    {
        model: "BMW X5",
        carModel: "BMW X5",
        brand: "BMW",
        type: "SUV",
        price: 120,
        dailyRentalPrice: 120,
        transmission: "Automatic",
        fuel: "Diesel",
        fuelType: "Diesel",
        seats: 7,
        rating: 4.9,
        availability: "Available",
        image: "https://images.unsplash.com/photo-1617814076367-b759c7d7e738?w=800",
        imageUrl:
            "https://images.unsplash.com/photo-1617814076367-b759c7d7e738?w=800",
        location: {
            lat: 23.8103,
            lng: 90.4074,
            address: "Banani, Dhaka",
        },
        userName: "David Brown",
        userEmail: "david@example.com",
        bookingCount: 15,
        description: "Luxury SUV with premium features and comfort",
        dateAdded: new Date("2024-10-22T11:00:00Z"),
    },
    {
        model: "Nissan Leaf",
        carModel: "Nissan Leaf",
        brand: "Nissan",
        type: "Hatchback",
        price: 45,
        dailyRentalPrice: 45,
        transmission: "Automatic",
        fuel: "Electric",
        fuelType: "Electric",
        seats: 5,
        rating: 4.4,
        availability: "Available",
        image: "https://images.unsplash.com/photo-1593941707882-a5bba14938c7?w=800",
        imageUrl:
            "https://images.unsplash.com/photo-1593941707882-a5bba14938c7?w=800",
        location: {
            lat: 23.7808,
            lng: 90.4217,
            address: "Motijheel, Dhaka",
        },
        userName: "Emma Davis",
        userEmail: "emma@example.com",
        bookingCount: 21,
        description: "Eco-friendly electric hatchback perfect for city driving",
        dateAdded: new Date("2024-10-23T16:45:00Z"),
    },
    {
        model: "Ford Mustang",
        carModel: "Ford Mustang",
        brand: "Ford",
        type: "Sports",
        price: 95,
        dailyRentalPrice: 95,
        transmission: "Manual",
        fuel: "Petrol",
        fuelType: "Petrol",
        seats: 4,
        rating: 4.7,
        availability: "Available",
        image: "https://images.unsplash.com/photo-1584345604476-8ec5f56e5ab9?w=800",
        imageUrl:
            "https://images.unsplash.com/photo-1584345604476-8ec5f56e5ab9?w=800",
        location: {
            lat: 23.8644,
            lng: 90.3968,
            address: "Airport Road, Dhaka",
        },
        userName: "Chris Wilson",
        userEmail: "chris@example.com",
        bookingCount: 12,
        description: "Iconic American muscle car with thrilling performance",
        dateAdded: new Date("2024-10-19T13:30:00Z"),
    },
    {
        model: "Toyota Prius",
        carModel: "Toyota Prius",
        brand: "Toyota",
        type: "Sedan",
        price: 55,
        dailyRentalPrice: 55,
        transmission: "Automatic",
        fuel: "Hybrid",
        fuelType: "Hybrid",
        seats: 5,
        rating: 4.6,
        availability: "Available",
        image: "https://images.unsplash.com/photo-1549399542-7e3f8b79c341?w=800",
        imageUrl:
            "https://images.unsplash.com/photo-1549399542-7e3f8b79c341?w=800",
        location: {
            lat: 23.7515,
            lng: 90.3911,
            address: "Mirpur, Dhaka",
        },
        userName: "Lisa Anderson",
        userEmail: "lisa@example.com",
        bookingCount: 28,
        description: "Fuel-efficient hybrid with excellent mileage",
        dateAdded: new Date("2024-10-21T08:20:00Z"),
    },
    {
        model: "Mercedes-Benz C-Class",
        carModel: "Mercedes-Benz C-Class",
        brand: "Mercedes-Benz",
        type: "Sedan",
        price: 110,
        dailyRentalPrice: 110,
        transmission: "Automatic",
        fuel: "Petrol",
        fuelType: "Petrol",
        seats: 5,
        rating: 4.8,
        availability: "Booked",
        image: "https://images.unsplash.com/photo-1618843479313-40f8afb4b4d8?w=800",
        imageUrl:
            "https://images.unsplash.com/photo-1618843479313-40f8afb4b4d8?w=800",
        location: {
            lat: 23.7936,
            lng: 90.4066,
            address: "Mohakhali, Dhaka",
        },
        userName: "Robert Taylor",
        userEmail: "robert@example.com",
        bookingCount: 19,
        description: "Elegant luxury sedan with advanced technology",
        dateAdded: new Date("2024-10-17T15:10:00Z"),
    },
    {
        model: "Chevrolet Suburban",
        carModel: "Chevrolet Suburban",
        brand: "Chevrolet",
        type: "SUV",
        price: 100,
        dailyRentalPrice: 100,
        transmission: "Automatic",
        fuel: "Diesel",
        fuelType: "Diesel",
        seats: 8,
        rating: 4.5,
        availability: "Available",
        image: "https://images.unsplash.com/photo-1519641471654-76ce0107ad1b?w=800",
        imageUrl:
            "https://images.unsplash.com/photo-1519641471654-76ce0107ad1b?w=800",
        location: {
            lat: 23.7272,
            lng: 90.4081,
            address: "Jatrabari, Dhaka",
        },
        userName: "Jennifer Lee",
        userEmail: "jennifer@example.com",
        bookingCount: 10,
        description: "Large SUV perfect for group travel and families",
        dateAdded: new Date("2024-10-16T12:40:00Z"),
    },
    {
        model: "Audi A4",
        carModel: "Audi A4",
        brand: "Audi",
        type: "Sedan",
        price: 90,
        dailyRentalPrice: 90,
        transmission: "Automatic",
        fuel: "Petrol",
        fuelType: "Petrol",
        seats: 5,
        rating: 4.7,
        availability: "Available",
        image: "https://images.unsplash.com/photo-1606664515524-ed2f786a0bd6?w=800",
        imageUrl:
            "https://images.unsplash.com/photo-1606664515524-ed2f786a0bd6?w=800",
        location: {
            lat: 23.8103,
            lng: 90.4125,
            address: "Gulshan, Dhaka",
        },
        userName: "Michael Chen",
        userEmail: "michael@example.com",
        bookingCount: 22,
        description: "Premium German engineering with sporty handling",
        dateAdded: new Date("2024-10-24T10:00:00Z"),
    },
    {
        model: "Hyundai Tucson",
        carModel: "Hyundai Tucson",
        brand: "Hyundai",
        type: "SUV",
        price: 60,
        dailyRentalPrice: 60,
        transmission: "Automatic",
        fuel: "Diesel",
        fuelType: "Diesel",
        seats: 5,
        rating: 4.3,
        availability: "Available",
        image: "https://images.unsplash.com/photo-1611859266238-4b98091d9d9b?w=800",
        imageUrl:
            "https://images.unsplash.com/photo-1611859266238-4b98091d9d9b?w=800",
        location: {
            lat: 23.7461,
            lng: 90.3742,
            address: "Dhanmondi, Dhaka",
        },
        userName: "Amy Rodriguez",
        userEmail: "amy@example.com",
        bookingCount: 16,
        description: "Modern compact SUV with great value",
        dateAdded: new Date("2024-10-25T09:30:00Z"),
    },
    {
        model: "Mazda CX-5",
        carModel: "Mazda CX-5",
        brand: "Mazda",
        type: "SUV",
        price: 70,
        dailyRentalPrice: 70,
        transmission: "Automatic",
        fuel: "Petrol",
        fuelType: "Petrol",
        seats: 5,
        rating: 4.6,
        availability: "Available",
        image: "https://images.unsplash.com/photo-1552519507-d0d1a9b3b6a3?w=800",
        imageUrl:
            "https://images.unsplash.com/photo-1552519507-d0d1a9b3b6a3?w=800",
        location: {
            lat: 23.8759,
            lng: 90.3795,
            address: "Uttara, Dhaka",
        },
        userName: "Kevin Martinez",
        userEmail: "kevin@example.com",
        bookingCount: 20,
        description: "Stylish SUV with premium interior and smooth drive",
        dateAdded: new Date("2024-10-14T14:15:00Z"),
    },
];

// Function to insert sample data
const insertSampleData = async (db) => {
    try {
        const carsCollection = db.collection("cars");

        // Clear existing data (optional - remove in production)
        // await carsCollection.deleteMany({});

        const result = await carsCollection.insertMany(sampleCars);
        console.log(
            `${result.insertedCount} sample cars inserted successfully`
        );

        return result;
    } catch (error) {
        console.error("Error inserting sample data:", error);
        throw error;
    }
};

module.exports = {
    sampleCars,
    insertSampleData,
};
